# Generated by Django 3.2.4 on 2021-10-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211017_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
