# Generated by Django 3.2.4 on 2021-10-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
    ]
