# Generated by Django 3.2.4 on 2021-10-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
